using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace DataFetcher;

/// <summary>
/// Simple HTTP Factory for fetching and deserializing JSON data
/// Generated by Claude :-)
/// </summary>
public static class HttpFactory
{
    private static readonly HttpClient _httpClient = new()
    {
        Timeout = TimeSpan.FromSeconds(30)
    };

    private static readonly JsonSerializerOptions _jsonOptions = new()
    {
        PropertyNameCaseInsensitive = true,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
    };

    /// <summary>
    /// Fetches JSON data from the specified URL and deserializes it to type T
    /// </summary>
    /// <typeparam name="T">The type to deserialize the JSON response into</typeparam>
    /// <param name="url">The URL to fetch data from</param>
    /// <param name="cancellationToken">Cancellation token for the request</param>
    /// <returns>Deserialized object of type T</returns>
    public static async Task<T?> FetchAsync<T>(string url, CancellationToken cancellationToken = default)
    {
        try
        {
            var response = await _httpClient.GetAsync(url, cancellationToken);
            response.EnsureSuccessStatusCode();

            // string debug = await response.Content.ReadAsStringAsync();
            // var bytes = await response.Content.ReadAsByteArrayAsync();
            // string bytesDebug = string.Join(',', bytes);

            return await response.Content.ReadFromJsonAsync<T>(_jsonOptions, cancellationToken);
        }
        catch (HttpRequestException ex)
        {
            throw new HttpRequestException($"Error fetching data from {url}: {ex.Message}", ex);
        }
        catch (JsonException ex)
        {
            throw new JsonException($"Error deserializing JSON response from {url}: {ex.Message}", ex);
        }
    }

    /// <summary>
    /// Fetches data as string.
    /// Parse the results later to avoid deserializing errors while fetching live data.
    /// Tackle deserialization errors later.
    /// </summary>
    /// <typeparam name="T">The type to deserialize the JSON response into</typeparam>
    /// <param name="url">The URL to fetch data from</param>
    /// <param name="cancellationToken">Cancellation token for the request</param>
    /// <returns>Deserialized object of type T</returns>
    public static async Task<string> FetchAsString(string url, CancellationToken cancellationToken = default)
    {
        try
        {
            var response = await _httpClient.GetAsync(url, cancellationToken);
            response.EnsureSuccessStatusCode();

            // string debug = await response.Content.ReadAsStringAsync();
            // var bytes = await response.Content.ReadAsByteArrayAsync();
            // string bytesDebug = string.Join(',', bytes);

            return await response.Content.ReadAsStringAsync();
        }
        catch (HttpRequestException ex)
        {
            throw new HttpRequestException($"Error fetching data from {url}: {ex.Message}", ex);
        }
        catch (JsonException ex)
        {
            throw new JsonException($"Error deserializing JSON response from {url}: {ex.Message}", ex);
        }
    }

    /// <summary>
    /// Fetches JSON data with custom headers
    /// </summary>
    public static async Task<T?> FetchAsync<T>(string url, Dictionary<string, string> headers, CancellationToken cancellationToken = default)
    {
        using var request = new HttpRequestMessage(HttpMethod.Get, url);
        
        foreach (var header in headers)
        {
            request.Headers.TryAddWithoutValidation(header.Key, header.Value);
        }

        try
        {
            var response = await _httpClient.SendAsync(request, cancellationToken);
            response.EnsureSuccessStatusCode();
            
            return await response.Content.ReadFromJsonAsync<T>(_jsonOptions, cancellationToken);
        }
        catch (HttpRequestException ex)
        {
            throw new HttpRequestException($"Error fetching data from {url}: {ex.Message}", ex);
        }
        catch (JsonException ex)
        {
            throw new JsonException($"Error deserializing JSON response from {url}: {ex.Message}", ex);
        }
    }

    /// <summary>
    /// Posts JSON data and returns deserialized response
    /// </summary>
    public static async Task<TResponse?> PostAsync<TRequest, TResponse>(string url, TRequest data, CancellationToken cancellationToken = default)
    {
        try
        {
            var response = await _httpClient.PostAsJsonAsync(url, data, _jsonOptions, cancellationToken);
            response.EnsureSuccessStatusCode();
            
            return await response.Content.ReadFromJsonAsync<TResponse>(_jsonOptions, cancellationToken);
        }
        catch (HttpRequestException ex)
        {
            throw new HttpRequestException($"Error posting data to {url}: {ex.Message}", ex);
        }
        catch (JsonException ex)
        {
            throw new JsonException($"Error deserializing JSON response from {url}: {ex.Message}", ex);
        }
    }

    /// <summary>
    /// Configure the HttpClient (call once at startup if needed)
    /// </summary>
    public static void ConfigureClient(Action<HttpClient> configure)
    {
        configure(_httpClient);
    }
}